default: &default
  adapter:  postgresql
  encoding: utf8
  schema:   edools
  database: postgres
  port:     5432

development:
  <<: *default
  username: gpweb
  host:     127.0.0.1
  password: '5iedo5noTCDFgpweb'

test:
  <<: *default
  username: gpweb
  host:     127.0.0.1
  password: '5iedo5noTCDFgpweb'

production:
  <<: *default
  username: gpweb
  host:     192.168.1.8
  password: <%= ENV['GPWEB_PROD_PASSWORD']  %>
